export const actionType = {
  SET_DOCTORS: 'SET_DOCTORS',
  CLEAR_DOCTORS: 'CLEAR_DOCTORS',

  SET_DETAIL_DOCTOR: 'SET_DETAIL_DOCTOR',

  GET_LIST_DOCTOR: 'GET_LIST_DOCTOR',
  ERROR_FETCH: 'ERROR_FETCH',
  SUCCESS_FETCH: 'SUCCESS_FETCH',
  LOADING_FETCH: 'LOADING_FETCH',
  RESET_LIST_DOCTOR: 'RESET_LIST_DOCTOR',
  UPDATE_LIST_DOCTOR: 'UPDATE_LIST_DOCTOR',
};
