export const actionType = {
  GET_LIST_DOCTOR: 'GET_LIST_DOCTOR',
  ERROR_FETCH: 'ERROR_FETCH',
  SUCCESS_FETCH: 'SUCCESS_FETCH',
  LOADING_FETCH: 'LOADING_FETCH',
  RESET_LIST_DOCTOR: 'RESET_LIST_DOCTOR',
  UPDATE_LIST_DOCTOR: 'UPDATE_LIST_DOCTOR',

  UPDATE_LIST_HOSPITAL: 'UPDATE_LIST_HOSPITAL',
  UPDATE_LIST_SPECIALIZATION: 'UPDATE_LIST_SPECIALIZATION',
};
